#!/usr/bin/env bash
# This script manages the manage_my_process script

case "$1" in
    start)
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill "$(cat /tmp/my_process.pid)"
        rm /tmp/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        kill "$(cat /tmp/my_process.pid)"
        rm /tmp/my_process.pid
        ./manage_my_process &
        echo $! > /tmp/my_process.pid
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
