#!/usr/bin/env bash
# This script handles multiple signals and manages a PID file
echo "$$" > /tmp/myscript.pid

trap "echo 'Y U no love me?!'" SIGINT
trap "echo 'I hate the kill command'; rm /tmp/myscript.pid; exit" SIGTERM
trap "rm /tmp/myscript.pid; exit" SIGQUIT

while true; do
    echo "To infinity and beyond"
    sleep 2
done
